name: push

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alpine_ver: [latest]
        jre_ver: [17-jre-headless, 8-jre-base]
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - id: get-id
        run: |
          id=$(echo ${{ matrix.jre_ver }} | cut -d- -f1)
          echo "::set-output name=id::$id"
      - run: echo "${{steps.get-id.outputs.id}}"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            ALPINE_VERSION=${{ matrix.alpine_ver }}
            JRE_VERSION=${{ matrix.jre_ver }}
          push: true
          tags: s3vt/java:${{ steps.get-id.outputs.id }}
  update-readme:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3.1.0
        with: 
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: peterevans/dockerhub-description
          short-description: ${{ github.event.repository.description }}
